const Constants = Object.freeze({
    SCREEN_HEIGHT: 24,
    AID: {
        NO_AID: "NO_AID",
        STRUCTURED_FIELD: "STRUCTURED_FIELD",
        TRIGGER_ACTION: "TRIGGER_ACTION",
        SYSREQ: "SYSREQ",
        PF1: "PF1",
        PF2: "PF2",
        PF3: "PF3",
        PF4: "PF4",
        PF5: "PF5",
        PF6: "PF6",
        PF7: "PF7",
        PF8: "PF8",
        PF9: "PF9",
        PF10: "PF10",
        PF11: "PF11",
        PF12: "PF12",
        PF13: "PF13",
        PF14: "PF14",
        PF15: "PF15",
        PF16: "PF16",
        PF17: "PF17",
        PF18: "PF18",
        PF19: "PF19",
        PF20: "PF20",
        PF21: "PF21",
        PF22: "PF22",
        PF23: "PF23",
        PF24: "PF24",
        PA1: "PA1",
        PA2: "PA2",
        PA3: "PA3",
        CLEAR: "CLEAR",
        CLEAR_PARTITION: "CLEAR_PARTITION",
        ENTER: "ENTER",
    }
});

export default Constants;
